
name: 'open_alex_authors'
version: '1.0.0'
config-version: 2

profile: 'open_alex_authors'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"


models:
  open_alex_authors:
    stg_authors_cited:
      +materialized: table
    stg_authors_concepts_cited:
      +materialized: table
    number_of_authors:
      +materialized: table
