open_alex_authors:

  target: dev
  outputs:
    dev:
      type: duckdb
      path: 'open_alex_authors.duckdb'
      threads: 1
      extensions:
        - httpfs
    prod:
      type: duckdb
      path: "md:open_alex_authors"
