
version: 2

models:
  - name: authors
    description: "author records"

  - name: author_ids
    description: "author ids"

  - name: authors_counts_by_year
    description: "distinct number of authors from each year"