
version: 2

sources:
  - name: open_alex_authors
    schema: main
    description: "Latest OpenAlex author data snapshot"
    meta:
      external_location: "read_json_auto('s3://openalex/data/authors/updated_date=2023-08-15/*.gz', format='newline_delimited', compression='gzip')"
    tables:
      - name: authors
      - name: authors_concepts
      - name: authors_counts_by_year
      - name: authors_ids


