
version: 2

sources:
  - name: open_alex_snapshot
    schema: main
    description: "Latest OpenAlex data snapshot"
    meta:
      external_location: read_ndjson_auto('./february_2024_snapshot/data/authors/updated_date=2023-07-*/*.gz')
    tables:
      - name: raw_authors
        meta:
          external_location: > 
            read_ndjson('/Volumes/8TB 1/february_2024_snapshot/authors/*/*.gz',
            columns = {
              id: 'VARCHAR',
              orcid: 'VARCHAR',
              display_name: 'VARCHAR',
              display_name_alternatives: 'VARCHAR[]',
              works_count: 'BIGINT',
              cited_by_count: 'BIGINT',
              most_cited_work: 'VARCHAR',
              ids: 'STRUCT(openalex VARCHAR, orcid VARCHAR, scopus VARCHAR)',
              last_known_institution: 'STRUCT(id VARCHAR, ror VARCHAR, display_name VARCHAR, country_code VARCHAR, type VARCHAR, lineage VARCHAR[])',
              counts_by_year: 'STRUCT(year VARCHAR, works_count BIGINT, oa_works_count BIGINT, cited_by_count BIGINT)[]',
              works_api_url: 'VARCHAR',
              updated_date: 'DATE',
              created_date: 'DATE',
              updated: 'VARCHAR'
            })
          formatter: oldstyle
      - name: raw_concepts
        meta:
          external_location: read_ndjson_auto('/Volumes/8TB 1/december_2023_snapshot/data/concepts/*/*.gz')
      - name: raw_domains
        meta:
          external_location: read_ndjson_auto('/Volumes/8TB 1/february_2024_snapshot/domains/*/*.gz')
      - name: raw_fields
        meta:
          external_location: read_ndjson_auto('/Volumes/8TB 1/february_2024_snapshot/fields/*/*.gz')
      - name: raw_funders
        meta:
          external_location: > 
            read_ndjson('/Volumes/8TB 1/february_2024_snapshot/funders/*/*.gz',
            columns = {
            id: 'VARCHAR',
            display_name: 'VARCHAR',
            ids: 'STRUCT(openalex VARCHAR, wikidata VARCHAR, crossref BIGINT, doi VARCHAR, ror VARCHAR)',
            country_code: 'VARCHAR',
            description: 'VARCHAR',
            roles: 'STRUCT(role VARCHAR, id VARCHAR, works_count BIGINT)[]',
            works_count: 'BIGINT',
            cited_by_count: 'BIGINT',
            updated_date: 'DATE',
            created_date: 'DATE',
            updated: 'VARCHAR'
            })
          formatter: oldstyle
      - name: raw_institutions
        meta:
          external_location: > 
            read_ndjson('/Volumes/8TB 1/february_2024_snapshot/institutions/*/*.gz',
            columns = {
            id: 'VARCHAR',
            ror: 'VARCHAR',
            display_name: 'VARCHAR',
            country_code: 'VARCHAR',
            type: 'VARCHAR',
            homepage_url: 'VARCHAR',
            image_url: 'VARCHAR',
            image_thumbnail_url: 'VARCHAR',
            display_name_acronyms: 'VARCHAR[]',
            display_name_alternatives: 'VARCHAR[]',
            works_count: 'BIGINT',
            cited_by_count: 'BIGINT',
            ids: 'STRUCT(openalex VARCHAR, ror VARCHAR, grid VARCHAR, wikipedia VARCHAR, wikidata VARCHAR, mag BIGINT)',
            geo: 'STRUCT(city VARCHAR, geonames_city_id VARCHAR, region VARCHAR, country_code VARCHAR, country VARCHAR, latitude DOUBLE, longitude DOUBLE)',
            associated_institutions: 'STRUCT(id VARCHAR, ror VARCHAR, display_name VARCHAR, country_code VARCHAR, "type" VARCHAR, relationship VARCHAR, lineage VARCHAR[])[]',
            counts_by_year: 'STRUCT(year VARCHAR, works_count BIGINT, oa_works_count BIGINT, cited_by_count BIGINT)[]',
            works_api_url: 'VARCHAR',
            updated_date: 'DATE'
            })
          formatter: oldstyle
      - name: raw_publishers
        meta:
          external_location: read_ndjson_auto('/Volumes/8TB 1/february_2024_snapshot/publishers/*/*.gz')
      - name: raw_sources
        meta:
          external_location: read_ndjson_auto('/Volumes/8TB 1/february_2024_snapshot/sources/*/*.gz')
      - name: raw_subfields
        meta:
          external_location: > 
            read_ndjson('/Volumes/8TB 1/february_2024_snapshot/subfields/*/*.gz',
            columns = {
              id: 'VARCHAR',
              display_name: 'VARCHAR',
              description: 'VARCHAR',
              display_name_alternatives: 'VARCHAR[]',
              ids: 'STRUCT(wikidata VARCHAR, wikipedia VARCHAR)',
              works_count: 'BIGINT',
              cited_by_count: 'BIGINT',
              field: 'STRUCT(id VARCHAR, display_name VARCHAR)',
              domain: 'STRUCT(id VARCHAR, display_name VARCHAR)',
              updated_date: 'DATE',
              created_date: 'DATE',
              updated: 'VARCHAR'
            })
          formatter: oldstyle
      - name: raw_topics
        meta:
          external_location: > 
            read_ndjson('/Volumes/8TB 1/february_2024_snapshot/topics/*/*.gz',
            columns = {
              id: 'VARCHAR',
              display_name: 'VARCHAR',
              subfield: 'STRUCT(id VARCHAR, display_name VARCHAR)',
              field: 'STRUCT(id VARCHAR, display_name VARCHAR)',
              domain: 'STRUCT(id VARCHAR, display_name VARCHAR)',
              description: 'VARCHAR',
              keywords: 'VARCHAR[]',
              ids: 'STRUCT(openalex VARCHAR, wikipedia VARCHAR)',
              updated_date: 'DATE',
              created_date: 'DATE',
              updated: 'VARCHAR'
            })
          formatter: oldstyle
      - name: raw_works
        meta:
          external_location: > 
            read_ndjson('/Volumes/8TB 1/february_2024_snapshot/works/*/*.gz',
            columns = {
              id: 'VARCHAR',
              doi: 'VARCHAR',
              title: 'VARCHAR',
              display_name: 'VARCHAR',
              publication_year: 'BIGINT',
              publication_date: 'DATE',
              primary_location: 'STRUCT(source STRUCT(id VARCHAR), pdf_url VARCHAR, landing_page_url VARCHAR, is_oa BOOLEAN, "version" VARCHAR, license VARCHAR)',
              ids: 'STRUCT(openalex VARCHAR, doi VARCHAR, pmid VARCHAR, mag BIGINT, arxiv_id VARCHAR, pmcid VARCHAR)',
              type: 'VARCHAR',
              cited_by_count: 'BIGINT',
              authorships: 'STRUCT(author_position VARCHAR, author STRUCT(id VARCHAR), institutions STRUCT(id VARCHAR, display_name VARCHAR, ror VARCHAR, country_code VARCHAR, type VARCHAR, lineage VARCHAR[])[])[]',
              biblio: 'STRUCT(volume VARCHAR, issue VARCHAR, first_page VARCHAR, last_page VARCHAR)',
              is_retracted: 'BOOLEAN',
              is_paratext: 'BOOLEAN',
              mesh: 'STRUCT(is_major_topic BOOLEAN, descriptor_ui VARCHAR, descriptor_name VARCHAR, qualifier_ui VARCHAR, qualifier_name VARCHAR)[]',
              referenced_works: 'VARCHAR[]',
              related_works: 'VARCHAR[]',
              cited_by_api_url: 'VARCHAR',
              language: 'VARCHAR',
              updated_date: 'DATE',
              topics: 'STRUCT(id VARCHAR, display_name VARCHAR, score DOUBLE)[]',
              primary_topic: 'STRUCT(id VARCHAR, display_name VARCHAR, score DOUBLE)'
            })
          formatter: oldstyle
